version: '3'
services:
  db:
    image: postgres
    env_file:
      - ./docker-config/db/.env
    volumes:
      - ./docker-config/db/pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
  nginx:
    image: nginx:1.13
    volumes:
      - "./app:/var/www/html"
      - "./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
    depends_on:
      - php
  # Application service layer
  php:
    build:
      context: ./docker-config/php
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
        - db
  # Heroku to publish
  # herokucli:
  #   image: finalgene/heroku-cli
  #   volumes:
  #     - "./:/app"
  #     - "/var/run/docker:/var/run/docker"

      